version: 2.0.{build}
image: Visual Studio 2017
environment:
  logintoken:
    secure: Obg3zodrwhLuQuDjIuKQSi0zHViKrqjW92yP6T9ymgDt5HymUgQcODvzOJINy0qV
build:
  verbosity: minimal
install:
- ps: Start-FileDownload "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.2.0.1214/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip"
- cmd: 7z x sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip
build_script:
- dotnet restore source/FeatureToggle.Core/FeatureToggle.Core.csproj
- dotnet "SonarScanner.MSBuild.dll" begin /k:"FeatureToggle.Core" /d:sonar.organization="anuraj-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%logintoken% /d:sonar.exclusions="/wwwroot/lib/**" /d:sonar.cs.opencover.reportsPaths="C:/projects/featuretoggle-core/test/FeatureToggle.Core.Tests/coverage.xml" /d:sonar.test.exclusions="test/**"
- dotnet build
- dotnet pack -c Release -o Output source/FeatureToggle.Core/FeatureToggle.Core.csproj
test_script:
- cmd: dotnet test test/FeatureToggle.Core.Tests/FeatureToggle.Core.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- cmd: dotnet "SonarScanner.MSBuild.dll" end /d:sonar.login=%logintoken%
artifacts:
- path: '\source\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: ailk/KPscyMWMXLEuizGE0EC1iIvsjHS7AS0DUjCSwcf3MWta8aXSGjCwsgqH+WV
    skip_symbols: true