version: 2.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
build_script:
- dotnet restore source/FeatureToggle.Core.csproj
- dotnet pack -c Release -o Output source/FeatureToggle.Core.csproj
test_script:
- cmd: dotnet test test/FeatureToggle.Core.Tests.csproj
artifacts:
- path: '\source\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: Fmmz/4Nyx73LFFQ75iOvA5giJtyri/Utyqi/mV9T5eCwMNtSkNHUGaYdsMMm2hFR
    skip_symbols: true