version: 2.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
build_script:
- dotnet restore FeatureToggle.Core.csproj
- dotnet pack -c Release -o Output FeatureToggle.Core.csproj
artifacts:
- path: '\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: 5XsCPhzHSChTdym1nwcZps3YxhZqySNztlUeT1rWtMmvrDM+R+WzxUkrYiMLBUVs
    skip_symbols: true